### ISSUE TITLE
Issue on IJ 241: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by rock3r** [tnorbye/kdoc-formatter#94]
Full exception, upon installing the plugin on IJC 241 EAP 2:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'kdocformatter.plugin.ReformatKDocAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.norbye.tor.kdocformatter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

**Comment by tnorbye** [comment]
Thanks for the report! I've uploaded a new version to the plugin center -- it might take a couple of days to get released but in the meantime you can also grab the plugin manually from https://github.com/tnorbye/kdoc-formatter/releases/tag/v1.6.2 .

**Comment by rock3r** [comment]
Awesome, thanks Tor!
